version: '3.8'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./_docker/nginx/conf.d:/etc/nginx/conf.d
            - ./public/storage:/var/www/public/storage
            - ./storage/app/public:/var/www/storage/app/public
        depends_on:
            - app
        container_name: ${APP_NAME}_nginx
        networks:
            app_net:

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            -   type: bind
                source: ./
                target: /var/www
            -   type: bind
                source: ./storage/app/public
                target: /var/www/public/storage
            #- ./:/var/www
        depends_on:
            - db
        container_name: ${APP_NAME}_app
        networks:
            app_net:

    db:
        image: mysql:8.0
        restart: always
        volumes:
            - db-data:/var/lib/mysql
            - db-data:/var/log/mysql
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "8101:3306"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: ${APP_NAME}_db
        networks:
            app_net:

networks:
    app_net:
        name: app_net

volumes:
    db-data:
        name: app_volume_db-data
